name: Deploy to AWS ECS

on:
  push:
    branches:
      - deploy # Se ejecuta automáticamente cuando haces push a esta rama

env:
  AWS_REGION: us-east-1                    # La región oficial de AWS Academy
  ECS_CLUSTER: innovatech-cluster          # El clúster que vas a crear en la U
  # NOTA: Abajo cambias el nombre del servicio y de la tarea según el repo (backend o frontend)
  ECS_SERVICE: innovatech-frontend-service 
  ECS_TASK_DEFINITION: innovatech-frontend-task 
  CONTAINER_NAME: frontend-container       # El nombre que le pusiste al contenedor en la Task Definition

jobs:
  deploy:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # 1. AUTENTICACIÓN EN AWS ACADEMY (Usando Secrets)
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # Obligatorio para cuentas de estudiante
        aws-region: ${{ env.AWS_REGION }}

    # 2. LOGIN EN EL REGISTRO PRIVADO DE AWS (Amazon ECR)
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # 3. CONSTRUIR LA IMAGEN DOCKER Y SUBIRLA A ECR
    - name: Build, Tag, and Push Image to ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        # NOTA: Cambia 'innovatech-frontend' por 'innovatech-backend' en el otro repositorio
        ECR_REPOSITORY: innovatech-frontend 
        IMAGE_TAG: ${{ github.sha }} # Usamos el ID del commit para que cada imagen sea única
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    # 4. DESCARGAR LA RECETA (Task Definition) ACTUAL DESDE AWS
    - name: Download Active Task Definition
      run: |
        aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION }} --query taskDefinition > task-definition.json

    # 5. ACTUALIZAR LA RECETA CON LA NUEVA IMAGEN DE DOCKER
    - name: Update Web Image in Task Definition
      id: render-task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}

    # 6. DESPLIEGUE FINAL EN ECS (Cero Downtime / Tolerante a fallos)
    - name: Deploy to Amazon ECS Service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.render-task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true 
